pipeline{
    agent any
    stages{
        
        stage("Print Branch"){
            steps{
                echo "Selected Branch is:- ${SelecteBranch}"
            }
        }
        stage("Git clone"){
            steps{
                sh "git clone https://github.com/dtank150/Jenkins-Task.git"
            }
        }
        stage("File Fetch"){
            steps{
                def filepath = "${env.WORKSPACE}"
                sh "cat ${filepath}"
            }
        }
    }
}
